version: '3'

services:
  web:
    image: webdevops/php-apache:5.6
    ports:
      - "8088:80"
    volumes:
      - .:/app # Lưu ý: Image này dùng thư mục /app thay vì /var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/app
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "test_db"